security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # Configure where users come from (database, LDAP, etc.)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Public access firewall for the login, register, and public home page
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: app_user_provider

            # Login form configuration
            form_login:
                login_path: /login
                check_path: /login_check
                enable_csrf: true
                csrf_token_id: authenticate
                csrf_parameter: _csrf_token
                username_parameter: _username
                password_parameter: _password
                default_target_path: dashboard

            logout:
                path: security_logout
                target: home

            # Session parameters for security
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week
                path:     /
                always_remember_me: false

    access_control:
        # Allowing unrestricted access to login, register, and home pages
        - { path: ^/login$, roles: PUBLIC_ACCESS_CONTROL }
        - { path: ^/register$, roles: PUBLIC_ACCESS_CONTROL }
        - { path: ^/$, roles: PUBLIC_ACCESS_CONTROL }

        # Only authenticated users can access logout
        - { path: ^/logout$, roles: PUBLIC_ACCESS_CONTROL }

        # Only users with ROLE_USER can access these pages
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/job-offers, roles: ROLE_USER }
        - { path: ^/linkedin-message, roles: ROLE_USER }
        - { path: ^/cover-letter, roles: ROLE_USER }
        - { path: ^/kanban, roles: ROLE_USER }
        - { path: ^/api/job-offers/update-status, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # Configure how users are authenticated
    # (e.g. login form, API token, etc.)
    access_decision_manager:
        strategy: unanimous

# Security tokens for CSRF protection
framework:
    csrf_protection:
        enabled: true