security:
    # Encoders to hash passwords
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Main user provider
    providers:
        # In-memory or database provider
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Firewalls
    firewalls:
        # Main firewall
        main:
            lazy: true
            # Use form_login to authenticate users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    # Access control
    access_control:
        # Allow everyone to access the home page
        - { path: ^/, roles: PUBLIC_ACCESS }
        # Allow access to the login and registration pages for everyone
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        # Protect the dashboard and all job offers routes for authenticated users
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/job-offers, roles: ROLE_USER }
        # Allow access to LinkedInMessage and CoverLetter generation for users
        - { path: ^/linkedin-message/generate, roles: ROLE_USER }
        - { path: ^/cover-letter/generate, roles: ROLE_USER }
        # Allow users to access their own resources
        - { path: ^/linkedin-message/, roles: ROLE_USER }
        - { path: ^/cover-letter/, roles: ROLE_USER }
        # Other routes requiring user authentication
        - { path: ^/kanban, roles: ROLE_USER }
        # Allow API calls for authenticated users
        - { path: ^/api, roles: ROLE_USER }